services:
  db:
    image: postgres:16.3
    container_name: gogarage-db
    env_file:
      - app.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    container_name: gogarage-redis
    ports:
      - "6376:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning", "--requirepass", "$REDIS_PASSWORD"]

volumes:
  db-data: